---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
    - gulpfile.js
    - test/
  eslint:
    enabled: true
  fixme:
    enabled: true
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.less"
  - "**.scss"
  - "**.sss"
  - "**.js"
exclude_paths:
- app/vendor/
- node_modules/
- scripts/
